Pipedrive docs
dlt-hub/pipelines pull request #15
Opened 2023-02-19 15:14 UTC by AmanGuptAnalytics

To update the pipedrice documentation.

2023-02-21 17:25 UTC, adrianbr requested changes

2023-02-21 17:25 UTC, adrianbr commented on pipelines/pipedrive/ReadMe.md
> +                                                      —END OF GUIDE, THANK YOU—
please remove this line :)

2023-02-22 02:58 UTC, AmanGuptAnalytics commented on pipelines/pipedrive/ReadMe.md
> +                                                      —END OF GUIDE, THANK YOU—
Removed.

2023-02-22 12:49 UTC, adrianbr approved these changes

2023-02-23 08:56 UTC, merged