Add google analytics pipeline (ga4)
dlt-hub/pipelines pull request #54
Opened 2023-03-28 08:52 UTC by redicane

2023-04-11 14:27 UTC, rudolfix requested changes
This is really close. Please rebase on newest master and fix the poetry lock conflict (you can just add the dependency again)

2023-04-11 14:27 UTC, rudolfix commented on pipelines/google_analytics/helpers/credentials.py
> +            self.access_token = google.refresh_token(token_url="https://oauth2.googleapis.com/token", refresh_token=self.refresh_token, **extra)["access_token"]
please add scopes and redirect url to config

2023-04-11 17:40 UTC, rudolfix requested changes

2023-04-11 17:40 UTC, rudolfix commented on pipelines/google_analytics/__init__.py
> +    if not start_date:
why do you need state here? what is the purpose to restart from previous date? if there is no real use for let's remove it. also @adrianbr did you request that?

2023-04-11 17:40 UTC, rudolfix commented on pipelines/google_analytics/__init__.py
> +        resource_list.append(dlt.resource(basic_report(client=client, rows_per_page=rows_per_page, property_id=property_id, dimensions=dimensions, metrics=metrics,
do we really want to replace reports? if you do them daily I assume you want to keep daily reports. what is a typical use case @adrianbr ? running this daily and keep reports for given day?

2023-04-12 09:25 UTC, redicane commented on pipelines/google_analytics/__init__.py
> +    if not start_date:
Hey @rudolfix, 

The idea here was to have the chance to run this periodically (like with Zendesk) and not have to input start and end dates manually. It is just extra functionality on loading the resource.

2023-04-12 13:59 UTC, adrianbr commented
Common use case we need to support
1. All requests should include date unless they already include DateHour or DateHourMinute
2. We should not load partial dates such as Today (today is not complete)
3. we do not need selected periods loaded. Incremental loading should always load from start date until last complete period (yesterday)
4. IMO we should not start with merge but with append loading. Load from start/default/last val to yesterday.
5. Merge loading is based on rules that may not apply to GA4 - let's do it once we have specs from a user such as Hans. Merge loading would always replace last X weeks of data to refresh data for which events arrived late. I am not sure this is still an issue in GA4 and 2023.

2023-04-14 13:26 UTC, rudolfix commented
@adrianbr I think it is not clear how incremental loading should work from pipeline user perspective. we'll have identical problems in all pipelines like that

> we do not need selected periods loaded. Incremental loading should always load from start date until last complete period (yesterday)

what does it mean? to me this means that we replace all the reports in the destination each time pipeline is run. and the start date is explicitly provided. if this is not the case then tell me

right now pipeline appends the data. if start date is specified it generates reports from start data until now and then appends
if it is not specified it generates the report form the beginning (here year 2001 AFAIK) and appends them. on next run it will use the 'yesterday' from the last run. so this is the incremental part. is this what you want? so to lead incrementally you never specify a start data. is that what you want?

i'm not able to review this further. also I see that dates can still be 'today' but we need to clear this first

2023-04-14 14:06 UTC, adrianbr commented
@rudolfix yes, this is how we want it loaded.

In short, it should load incrementally from
- If it loaded before: last loaded date
- if it did not load before: 
-   If there is a start date, start from there. Else, start from beginning of time. (year 2000 is fine)

2023-04-14 14:06 UTC, merged

2023-04-14 14:13 UTC, rudolfix commented
maybe you can write pseudo code how people would load incrementally with start date specified